# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v1

      # Setup JDK version
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Execute clean build
      - name: Clean
        run: ./gradlew :hadi-android:clean

      # Execute lint validation
      - name: Lint
        run: ./gradlew :hadi-android:lintDebug

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew :hadi-android:test
